project:
  type: book
  output-dir: docs
  
book:
  title: "Quantitative methods in corpus linguistics: A reader"
  author: "Vladimir Buskin"
  date: "2024-06-30"
  chapters:
    - part: "Introduction to R"
      chapters:
        - index.qmd
        - Exploring_RStudio.qmd
        - Vectors_Factors.qmd
        - Data_frames.qmd
        - Libraries.qmd
        - Importing_exporting.qmd
    - part: "Corpus linguistics with R"
      chapters:
        - Concordancing.qmd
    - part: "Descriptive statistics"
      chapters:
        - Variables.qmd
        - Categorical_data.qmd
        - Summary_statistics.qmd
        - Distributions.qmd
    - part: "Inferential statistics"
      chapters:
        - Hypothesis_testing.qmd
        - Chi_square_test.qmd
        - t_test.qmd
    - part: "Machine learning"
      chapters:
        - Linear_regression.qmd
        - Logistic_regression.qmd
        - Decision_trees_and_random_forests.qmd
    - part: "References"
      chapters:
        - references.qmd
        
        
bibliography: R.bib

code-block-font-size: 6pt

format:
  html:
    theme: yeti
  pdf:
    documentclass: scrreprt
    keep-tex: true  # Optionally keep the intermediate .tex file
    geometry: "left=3cm,right=3cm,top=2cm,bottom=2cm,heightrounded"  # Set margins
    fontsize: 11pt  # Set font size
    fontfamily: libertine  # Set a custom font
    header-includes:  # Add custom LaTeX preamble content
      - \usepackage{fancyhdr}
      - \pagestyle{fancy}
      - \fancyhf{}
      - \fancyhead[L]{\leftmark}
      - \fancyhead[R]{\thepage}
      - \fancyfoot[C]{Quantitative methods in corpus linguistics}
  

editor: visual

execute:
  freeze: auto
  warning: false
  message: false
code-overflow: wrap

