project:
  type: book
  output-dir: docs
  
book:
  title: "Quantitative methods in corpus linguistics"
  author: "Vladimir Buskin"
  date: "6/30/2024"
  chapters:
    - index.qmd
    - Vectors & Factors.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: yeti
  pdf:
    documentclass: scrreprt

editor: visual

execute:
  freeze: auto

