---
title: "Linguistic variables"
author: Thomas Brunner, Vladimir Buskin
format:
  html:
    self-contained: true
    theme: default
    toc: true
    number-sections: true
    slide-number: true
    incremental: false
    slide-level: 3
    scrollable: true
    
editor: visual
---

## What is a linguistic variable?

1.  **The classical view:** Labov (1972) defines a linguistic variable
    as "two ways of saying the same thing."

2.  **A restriction:** Meyerhoff (2009, p. 11) summarized, "In sum, a
    sociolinguistic variable can be defined as a linguistic variable
    that is constrained by social or non-linguistic factors..."

3.  **A more open view:** Kiesling (2011) argued, "Given the variability
    of what counts as a variable, we must define what counts as a
    variable more broadly than 'two or more ways of saying the same
    thing'. We will simply say that a linguistic variable is a choice or
    option about speaking in a speech community... Note that this
    definition does not in any way require us to state that the meaning
    be the same, although there should be some kind of equivalence
    noted."

::: callout-caution
## Discussion

Which of the following variables are good sociolinguistic variables, and
which of them are poor?

1.  /fɔːθ flɔː/ vs. /fɔːrθ flɔːr/
2.  *This enables him to preside over the process which I have
    described* vs. *This enables him to preside over the process that I
    have described* vs. *This enables him to preside over the process ∅
    I have described*.
3.  *The pair found the briefcase on a bus station bench at Bath central
    bus station.* vs. *The briefcase was found on a bus station bench at
    Bath central bus station by the pair.*
4.  *Art is after all the subject of attention for both critic and
    historian, even though the functions and methods of the two sorts of
    writer have drawn apart.* vs. *Art histories often make an attempt
    to keep to chronology, although the difficulties include the crucial
    fact that in art there is no clear sequence of events.* vs. *Many of
    his readers approved his sensitive and appreciative understanding of
    paintings, though without sharing his political views.*
5.  /pleɪŋ/ vs. /pleɪn/
6.  \[tʰ\] in /tɔp/ vs. \[t\] in *stop*.

:::

## The principle of accountability

::: callout-caution
## Task

Two linguists aim to study the preference for passives among
men and women. They extract all the passives from 500,000 words of male
speech and all passives from 500,000 words of female speech and report
the results. **What's wrong?**

:::

## Subtypes of variables

### Linguistic perspective

1.  phonetic/phonological
2.  morphological
3.  syntactic
4.  pragmatic

### Sociolinguistic perspective

Sociolinguistic variables also differ with regard to their **salience**
in society.

1.  **Stereotypes** are strongly socially marked and part of popular
    discourse about language.
    -   *h*-dropping in Cockney
    -   Canadian *eh* at the end of sentences
    -   Australian *dinkum*: *I was fair dinkum about my interest in
        their culture* 'authentic, genuine'
2.  **Markers** show both social and style stratification; all members
    of a society react similarly in taking care to **avoid the pattern**
    in **formal registers**.
    -   

        (r) 

    -   (th)
3.  **Indicators** differentiate social groups. However, people are not
    aware of them and therefore do not avoid them in formal registers.
    -   Same vowel in *God* and *Guard* in New York City

> Taken from Mesthrie, Rajend, et al. *Introducing Sociolinguistics*.
> Edinburgh University Press, 2009.

## Statistical perspective

### Dependent and independent variables

**Task:** Decide which of the variables are **independent**, and which
are **dependent variables**!

|                         | Kenyan speakers | Singaporean speakers |
|-------------------------|-----------------|----------------------|
| Average sentence length | 10.5            | 9.8                  |

|            | male | female |
|------------|------|--------|
| *actually* | 65   | 98     |
| *possibly* | 55   | 77     |
| *really*   | 54   | 55     |

| Question: English is the most important language today. | **strongly agree** | **agree** | **neutral** | **disagree** | **strongly disagree** |
|---------------------|----------|----------|----------|----------|----------|
| N                                                       | 12                 | 33        | 58          | 12           | 8                     |

### Interval, ordinal, and nominal

1.  COMPLEXITY (ordinal)
    -   *the book* (low)
    -   *the brown book* (middle)
    -   *the book I had bought in Europe* (high)
2.  LENGTH (interval)
    -   *book* (1)
    -   *the book* (2)
    -   *the book I had bought in Europe* (7)
3.  ANIMACY (nominal)
    -   *He picked up **the book**.*
    -   *He picked **his dad** up.*

> Cf. Gries, Stefan Th. *Statistics for Linguistics with R*. De Gruyter
> Mouton, 2013, p. 9.

**Task:** Now, go back to Tables 1--3 and decide which of the variables
are **interval variables**, **ordinal** or **nominal** variables!

## Many morphosyntactic variables in English

| Variable                               | Example                                                                              |
|--------------------------------|----------------------------------------|
| Indefinite Pronouns                    | *everybody* vs. *everyone*                                                           |
| Case and order of coordinated pronouns | *my husband and I* vs. *my husband and me* vs. *me and my husband*                   |
| *that* vs. zero complementation        | *I don't think **that**/Ø it's a problem.*                                           |
| *that* vs. gerundial complementation   | *remember **that*** vs. *remember **V-ing***; *try to* vs. *try and* vs. *try V-ing* |
| Particle placement                     | *set the computer up* vs. *set up the computer*                                      |
| The dative alternation                 | *give the book to John* vs. *give John the book*                                     |
| The genitive alternation               | *John's house* vs. *the house of John*                                               |
| Relativization strategies              | *wh*-word vs. *that* vs. Ø                                                           |
| Analytic vs. synthetic comparatives    | *warmer* vs. *more scary*                                                            |
| Plural existentials                    | *there are some places* vs. *there's some places*                                    |
| Future temporal reference              | *will* vs. *going to* vs. progressive etc.                                           |
| Deontic modality                       | *must* vs. *have to* vs. *need to* vs. *got to* etc.                                 |
| Stative possession                     | *have* vs. *have got* vs. *got*                                                      |
| Quotatives                             | *say* vs. *be like* vs. *go* etc.                                                    |
| *not* vs. *no*                         | *not anybody* vs. *nobody*; *not anyone* vs. *no one*; *not anything* vs. *nothing*  |
| *NOT* vs. *AUX* contraction            | *that's not* vs. *that isn't* etc.                                                   |

> Taken from Szmrecsanyi, Benedikt. *Grammatical Variation in British
> English Dialects: A Study in Corpus-Based Dialectometry*. Cambridge
> University Press, 2021 (including most examples).
