{
  "hash": "9f1e4e3e16737b1f5710191bc59fd9da",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Concordancing\"\nauthor: Vladimir Buskin\nformat:\n  html:\n    self-contained: true\n    theme: default\n    toc: true\n    number-sections: true\n    slide-number: true\n    incremental: false\n    slide-level: 3\n    scrollable: true\n    \neditor: visual\n---\n\n\n\n## Using the `QuantedaApp`\n\nInstallation and usage instructions are available in this [GitHub\nrepository](https://github.com/VBuskin/quanteda_app).\n\n## Using the `quanteda` package in R\n\n### Preparation\n\n::: callout-warning\n### Working directory\n\nIn order for R to be able to recognise the data, it is crucial to set up\nthe working directory correctly.\n\n1.  Make sure your R-script **and** the corpus (e.g., 'ICE-GB') are\n    stored in the **same folder**.\n\n2.  In RStudio, now navigate to `Session` \\> `Set working directory` \\>\n    `To Source File Location`. This ensures that the folder where you\n    have placed your R-script will function as your working directory\n    until you close RStudio again.\n\nTo see your working directory in your files pane, click on `Files` \\>\n`'Blue wheel symbol'` \\> `Go to working directory`.\n:::\n\n### Loading the corpus\n\nTo load a corpus object into R, place it in your working directory and\nperform read it into your working environment with `readRDS()`. The\nICE-GB.RDS file you've been provided with has been pre-processed and\nsaved in this specific format for practical reasons.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nICE_GB <- readRDS(\"ICE_GB.RDS\")\n```\n:::\n\n\n\nIf you encounter any error messages, make sure you followed steps 1 and\n2 in the box above.\n\n### Concordancing\n\nIn order to perform concordances in R, we need to load the packages\nbelow.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load libraries\nlibrary(quanteda)\nlibrary(tidyverse)\n```\n:::\n\n\n\nNext, we use the `kwic()` function, which requires a corpus object and a\nsearch expression. Let's supply both:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Query the corpus\nquery1 <- kwic(ICE_GB, phrase(\"eat\"))\n```\n:::\n\n\n\nPrint the first few lines of our results with `head()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhead(query1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nKeyword-in-context with 6 matches.                                                            \n  [ICE_GB/S1A-006.txt, 785]           So I' d rather | eat |\n [ICE_GB/S1A-009.txt, 1198]              I must <, > | eat |\n  [ICE_GB/S1A-010.txt, 958]         to <, > actually | eat |\n  [ICE_GB/S1A-018.txt, 455] order one first and then | eat |\n  [ICE_GB/S1A-018.txt, 498]  A > The bargain hunting | eat |\n [ICE_GB/S1A-023.txt, 1853]       B > Oh name please | eat |\n                            \n beforehand just to avoid uh\n them < ICE-GB:S1A-009#71:  \n it for one' s              \n it and then sort of        \n < ICE-GB:S1A-018#29: 1     \n something <,, >            \n```\n\n\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|l|l|l|l}\n\\hline\ndocname & from & to & pre & keyword & post & pattern\\\\\n\\hline\nICE\\_GB/S1A-006.txt & 785 & 785 & So I ' d rather & eat & beforehand just to avoid uh & eat\\\\\n\\hline\nICE\\_GB/S1A-009.txt & 1198 & 1198 & I must < , > & eat & them < ICE-GB:S1A-009 \\#71 : & eat\\\\\n\\hline\nICE\\_GB/S1A-010.txt & 958 & 958 & to < , > actually & eat & it for one ' s & eat\\\\\n\\hline\nICE\\_GB/S1A-018.txt & 455 & 455 & order one first and then & eat & it and then sort of & eat\\\\\n\\hline\nICE\\_GB/S1A-018.txt & 498 & 498 & A > The bargain hunting & eat & < ICE-GB:S1A-018 \\#29 : 1 & eat\\\\\n\\hline\nICE\\_GB/S1A-023.txt & 1853 & 1853 & B > Oh name please & eat & something < , , > & eat\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\nFor a full screen display of the data frame, try `View()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nView(query1)\n```\n:::\n\n\n\n### Some basic statistics\n\nHow many tokens (= individual hits) does our query return?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(query1) # Token number corresponds to the number of rows in the data frame\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 53\n```\n\n\n:::\n:::\n\n\n\nHow many types (= distinct hits) does our query return?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(query1$keyword)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\neat Eat \n 52   1 \n```\n\n\n:::\n:::\n\n\n\nHow is the keyword distributed across corpus files?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquery_distrib <- table(query1$docname, query1$keyword)\n\nhead(query_distrib, n = 10)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    \n                     eat Eat\n  ICE_GB/S1A-006.txt   1   0\n  ICE_GB/S1A-009.txt   1   0\n  ICE_GB/S1A-010.txt   1   0\n  ICE_GB/S1A-018.txt   2   0\n  ICE_GB/S1A-023.txt   1   0\n  ICE_GB/S1A-025.txt   1   0\n  ICE_GB/S1A-038.txt   1   0\n  ICE_GB/S1A-046.txt   2   0\n  ICE_GB/S1A-047.txt   3   0\n  ICE_GB/S1A-051.txt   1   0\n```\n\n\n:::\n:::\n\n\n\n### Window size\n\nSome studies require careful examination of the preceding or following\ncontext of the keyword. We can easily adjust the `window` size to suit\nour needs:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nquery2 <- kwic(ICE_GB, phrase(\"eat\"), window = 20) \n```\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n\\begin{table}\n\\centering\n\\begin{tabular}[t]{l|r|r|l|l|l|l}\n\\hline\ndocname & from & to & pre & keyword & post & pattern\\\\\n\\hline\nICE\\_GB/S1A-006.txt & 785 & 785 & \\#49 : 1 : A > Yeah < ICE-GB:S1A-006 \\#50 : 1 : A > So I ' d rather & eat & beforehand just to avoid uh < , , > any problems there < ICE-GB:S1A-006 \\#51 : 1 : B > & eat\\\\\n\\hline\nICE\\_GB/S1A-009.txt & 1198 & 1198 & < , > in in the summer < ICE-GB:S1A-009 \\#70 : 1 : A > I must < , > & eat & them < ICE-GB:S1A-009 \\#71 : 1 : A > Yes < ICE-GB:S1A-009 \\#72 : 1 : B > You ought & eat\\\\\n\\hline\nICE\\_GB/S1A-010.txt & 958 & 958 & 1 : B > You know I mean it would seem to be squandering it to < , > actually & eat & it for one ' s own enjoyment < , , > < ICE-GB:S1A-010 \\#49 : 1 : A > Mm & eat\\\\\n\\hline\nICE\\_GB/S1A-018.txt & 455 & 455 & s so < ICE-GB:S1A-018 \\#27 : 1 : A > What you should do is order one first and then & eat & it and then sort of carry on from there < laughter > < , > by which time you wouldn't & eat\\\\\n\\hline\nICE\\_GB/S1A-018.txt & 498 & 498 & second anyway so < laugh > < , > < ICE-GB:S1A-018 \\#28 : 1 : A > The bargain hunting & eat & < ICE-GB:S1A-018 \\#29 : 1 : B > So all right what did I have < ICE-GB:S1A-018 \\#30 : 1 & eat\\\\\n\\hline\nICE\\_GB/S1A-023.txt & 1853 & 1853 & > I can't bear it < , , > < ICE-GB:S1A-023 \\#121 : 1 : B > Oh name please & eat & something < , , > < ICE-GB:S1A-023 \\#122 : 1 : A > Oh actually Dad asked me if < & eat\\\\\n\\hline\n\\end{tabular}\n\\end{table}\n\n\n:::\n:::\n\n\n\n### Saving your output\n\nYou can store your results in a spreadsheet file just as described in\n`Introduction to R > Import/export data`.\n\n-   **Microsoft Excel (.xlsx)**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(writexl)\n\nwrite_xlsx(query2, \"myresults1.xlsx\")\n```\n:::\n\n\n\n-   **LibreOffice** (.csv)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite.csv(query2, \"myresults1.csv\")\n```\n:::\n\n\n\nAs soon as you have annotated your data, you can load .xlsx files back\ninto R with `read_xlsx()` from the `readxl` package and .csv files using\nthe Base R function `read.csv()`.\n",
    "supporting": [
      "Concordancing_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}