{
  "hash": "6d04457237649eea229cb39b5292f15d",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"t-test\"\nauthor:\n  name: \"Vladimir Buskin\" \n  orcid: \"0009-0005-5824-1012\"\n  affiliation: \n    name: \"Catholic University of Eichstätt-Ingolstadt\"\n    department: \"English Language and Linguistics\"\nformat:\n  html:\n    self-contained: true\n    code-fold: false\n    theme: default\n    toc: true\n    toc-depth: 4\n    number-sections: true\n    slide-number: true\n    incremental: false\n    slide-level: 3\n    scrollable: true\neditor: visual\nbibliography: R.bib\n---\n\n\n## Preparation\n\n\n\n\n\n-   Load packages and data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(\"readxl\")\nlibrary(\"tidyverse\")\n\ndata_vowels <- read.csv(\"Vowels_Apache.csv\", sep = \"\\t\")\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n## The $t$-test\n\nSince the $\\chi^2$ measure exclusively works with categorical variables,\na separate test statistic is required if one of them is a continuous\nvariable. The $t$ statistic is often used for research questions\ninvolving differences between sample means. The way $t$ is calculated\ndepends on the sources of $X$ and $Y$: Do they originate from the same\nsample or from two (in-)dependent ones?\n\nFirst, we consider two **independent samples** from a population:\n\n-   Sample $X$ with the observations $\\{x_1, x_2, ..., {x_n}_1\\}$,\n    sample size $n_1$, sample mean $\\bar{x}$ and sample variance\n    $s^2_x$.\n\n-   Sample $Y$ with the observations $\\{y_1, y_2, ..., {y_n}_2\\}$,\n    sample size $n_2$, sample mean $\\bar{y}$ and sample variance\n    $s^2_y$.\n\n::: {.callout-note collapse=\"true\" title=\"Definition of the $t$-test\"}\nThe $t$-statistic after Welch is given by:\n\n$$\nt(x, y) = \\frac{|\\bar{x} - \\bar{y}|}{\\sqrt{\\frac{s^2_x}{n_1} + \\frac{s^2_y}{n_2}}} \n$$ {#eq-welch}\n\n-   If there is more than one observation for a given subject (e.g,\n    before and after an experiment), the samples are called\n    **dependent** or **paired**. The paired $t$-test assumes two\n    continuous variables $X$ and $Y$.\n\n-   In the paired test, the variable $d$ denotes the difference between\n    them, i.e., $x - y$. The corresponding test statistic is obtained\n    via\n\n$$\nt(x, y) = t(d) = \\frac{\\bar{d}}{s_d} \\sqrt{n}.\n$$ {#eq-paired}\n\nNote the difference $\\bar{d} = \\frac{1}{n}\\sum_{i=1}^n{d_i}$ and the\nvariance\n\n$$\ns^2_d = \\frac{\\sum_{i=1}^n({d_i} - \\bar{d})^2}{n-1}.\n$$ {#eq-diff-var}\n\nTraditionally, the $t$-test is based on the assumptions of ...\n\n1.  **Normality** and\n2.  **Variance homogeneity** (i.e., equal sample variances). Note that\n    this does not apply to the $t$-test after Welch, which can handle\n    unequal variances.\n:::\n\nThe implementation in R is very straightforward:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(data_vowels$HZ_F1 ~ data_vowels$SEX, paired = FALSE) # there is a significant difference!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  data_vowels$HZ_F1 by data_vowels$SEX\nt = 2.4416, df = 112.19, p-value = 0.01619\nalternative hypothesis: true difference in means between group F and group M is not equal to 0\n95 percent confidence interval:\n  8.403651 80.758016\nsample estimates:\nmean in group F mean in group M \n       528.8548        484.2740 \n```\n\n\n:::\n:::\n\n\n::: callout-important\nIf at least one assumption of the $t$-test has been violated, it is\nadvisable to use a non-parametric test such as the\n**Wilcoxon-Mann-Whitney (WMW) U-Test** instead. In essence, this test\ncompares the probabilities of encountering a value $x$ from sample $X$\nthat is greater than a value $y$ from sample $Y$. For details, see\n`?wilcox.test()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwilcox.test(data_vowels$HZ_F1 ~ data_vowels$SEX)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWilcoxon rank sum test with continuity correction\n\ndata:  data_vowels$HZ_F1 by data_vowels$SEX\nW = 2270, p-value = 0.01373\nalternative hypothesis: true location shift is not equal to 0\n```\n\n\n:::\n:::\n\n:::\n\n## Workflow in R\n\n### Define hypotheses\n\n-   $H_0:$ mean `F1 frequency` of men $=$ mean `F1 frequency` of women.\n\n-   $H_1:$ mean `F1 frequency` of men $\\ne$ mean `F1 frequency` of\n    women.\n\n### Descriptive overview\n\nWe select the variables of interest and proceed calculate the mean\n`F1 frequencies` for each level of `SEX`, requiring a grouped data\nframe.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Filter data so as to show only those observations that are relevant\ndata_vowels %>% \n  # Filter columns\n  select(HZ_F1, SEX) %>%\n    # Define grouping variable\n    group_by(SEX) %>% \n      # Compute mean and standard deviation for each sex\n      summarise(mean = mean(HZ_F1),\n                sd = sd(HZ_F1)) -> data_vowels_stats\n\nknitr::kable(data_vowels_stats)\n```\n\n::: {.cell-output-display}\n\n\n|SEX |     mean|        sd|\n|:---|--------:|---------:|\n|F   | 528.8548| 110.80099|\n|M   | 484.2740|  87.90112|\n\n\n:::\n:::\n\n::: {.cell ouput='true'}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Plot distributions\ndata_vowels_stats %>% \n  ggplot(aes(x = SEX, y = mean)) +\n    geom_col() +\n    geom_errorbar(aes(x = SEX,\n                    ymin = mean-sd,\n                    ymax = mean+sd), width = .2) +\n    theme_classic()\n```\n\n::: {.cell-output-display}\n![](t_test_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# Plot quartiles\ndata_vowels %>% \n  ggplot(aes(x = SEX, y = HZ_F1)) +\n    geom_boxplot() +\n    theme_classic()\n```\n\n::: {.cell-output-display}\n![](t_test_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n:::\n\n\n### Check $t$-test assumptions\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Normality\nshapiro.test(data_vowels$HZ_F1) # H0: data points follow the normal distribution; however, this test is pretty unreliable!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  data_vowels$HZ_F1\nW = 0.98996, p-value = 0.5311\n```\n\n\n:::\n\n```{.r .cell-code}\n# Check histogram\nggplot(data_vowels, aes(x = HZ_F1)) +\n  geom_histogram(bins = 30) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](t_test_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Variance homogeneity\nvar.test(data_vowels$HZ_F1 ~ data_vowels$SEX) # H0: variances are not too different from each other\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  data_vowels$HZ_F1 by data_vowels$SEX\nF = 1.5889, num df = 59, denom df = 59, p-value = 0.07789\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.949093 2.660040\nsample estimates:\nratio of variances \n          1.588907 \n```\n\n\n:::\n:::\n\n\n### Running the test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t-test for two independent samples \nt.test(data_vowels$HZ_F1 ~ data_vowels$SEX, paired = FALSE) # there is a significant difference between sample means!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  data_vowels$HZ_F1 by data_vowels$SEX\nt = 2.4416, df = 112.19, p-value = 0.01619\nalternative hypothesis: true difference in means between group F and group M is not equal to 0\n95 percent confidence interval:\n  8.403651 80.758016\nsample estimates:\nmean in group F mean in group M \n       528.8548        484.2740 \n```\n\n\n:::\n:::\n\n\n### Effect size\n\n**Cohen's** ***d*** is a possible effect size measure for continuous\ndata and is obtained by dividing the difference of both sample means by\nthe pooled standard deviation:\n\n$$\\frac{\\bar{x} - \\bar{y}}{\\sqrt{\\frac{{(n_1 - 1)s_x^2 + (n_2 - 1)s_y^2}}{{n_1 + n_2 - 2}}}}.$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncohen.d(data_vowels$HZ_F1, data_vowels$SEX) # see also ?cohen.d for more details\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCohen's d\n\nd estimate: 0.4457697 (small)\n95 percent confidence interval:\n     lower      upper \n0.07976048 0.81177897 \n```\n\n\n:::\n:::\n\n\n### Reporting the results\n\nAccording to a two-sample $t$-test, there is a significant difference\nbetween the mean `F1 frequencies` of male and female speakers of Apache\n($t = 2.44$, $df = 112.19$, $p < 0.05$). Therefore, $H_0$ will be\nrejected.\n\n\n",
    "supporting": [
      "t_test_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}